In [1]:
import numpy as np

In [2]:
X = np.random.normal(loc=1, scale=10, size=(1000, 50))

In [3]:
X

array([[ 23.6213802 ,   3.47100162,   2.63947852, ..., -14.85942632,
         -6.07679478,  21.49600931],
       [-11.38133603,   9.35429352,   9.10409948, ...,   1.89899434,
         20.32400724,  18.20633404],
       [ 24.19630042,   7.31242485,  -1.29112023, ...,  21.69878746,
         19.62237793,   2.30133076],
       ...,
       [ -5.86178559,   2.34525929,   8.560165  , ...,   5.38750226,
         -9.43658972, -20.29889343],
       [  6.40447436, -17.18831759, -17.73210074, ..., -16.21184841,
         -1.36980652,  16.523301  ],
       [ 27.99221804,  -3.71716261,  -9.08536679, ..., -10.59377946,
         -1.9172615 , -14.28926437]])

In [4]:
m = X.mean()
std = X.std()

In [5]:
X_norm = (X - m) / std

In [6]:
X_norm

array([[ 2.26644732,  0.24430421,  0.16085869, ..., -1.5952021 ,
        -0.71384209,  2.0531608 ],
       [-1.24616666,  0.83470792,  0.80960029, ...,  0.08654917,
         1.93554733,  1.7230333 ],
       [ 2.32414207,  0.62980106, -0.23358715, ...,  2.07351012,
         1.865137  ,  0.12692468],
       ...,
       [-0.69226536,  0.13133303,  0.75501504, ...,  0.43663005,
        -1.05100629, -2.14106683],
       [ 0.53868586, -1.82891242, -1.88348248, ..., -1.73092119,
        -0.24148353,  1.55413654],
       [ 2.70507231, -0.47704684, -1.01576015, ..., -1.1671333 ,
        -0.29642207, -1.53798486]])

In [7]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [8]:
X = np.array([row for row in Z if row.sum() > 10])

In [9]:
X

array([[1, 9, 3],
       [9, 9, 9],
       [4, 7, 1]])

In [10]:
E1 = np.eye(3)
E2 = np.eye(3)

In [11]:
np.vstack((E1, E2))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])